/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MemoryAnchor {
  export type MemorySnapshotStruct = {
    rootHash: BytesLike;
    epochNumber: BigNumberish;
    timestamp: BigNumberish;
    anchoredBy: AddressLike;
    label: string;
  };

  export type MemorySnapshotStructOutput = [
    rootHash: string,
    epochNumber: bigint,
    timestamp: bigint,
    anchoredBy: string,
    label: string
  ] & {
    rootHash: string;
    epochNumber: bigint;
    timestamp: bigint;
    anchoredBy: string;
    label: string;
  };
}

export interface MemoryAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorSnapshot"
      | "getLatestSnapshot"
      | "getSnapshotCount"
      | "getSnapshots"
      | "setSwarmGoal"
      | "snapshotCount"
      | "snapshots"
      | "swarmGoals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GoalSet" | "SnapshotAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorSnapshot",
    values: [string, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestSnapshot",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSnapshotCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSnapshots",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwarmGoal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshotCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshots",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "swarmGoals", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "anchorSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSnapshotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSnapshots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwarmGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snapshotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swarmGoals", data: BytesLike): Result;
}

export namespace GoalSetEvent {
  export type InputTuple = [
    swarmId: string,
    goal: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [swarmId: string, goal: string, timestamp: bigint];
  export interface OutputObject {
    swarmId: string;
    goal: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotAnchoredEvent {
  export type InputTuple = [
    swarmId: string,
    epochNumber: BigNumberish,
    rootHash: BytesLike,
    timestamp: BigNumberish,
    anchoredBy: AddressLike
  ];
  export type OutputTuple = [
    swarmId: string,
    epochNumber: bigint,
    rootHash: string,
    timestamp: bigint,
    anchoredBy: string
  ];
  export interface OutputObject {
    swarmId: string;
    epochNumber: bigint;
    rootHash: string;
    timestamp: bigint;
    anchoredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemoryAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): MemoryAnchor;
  waitForDeployment(): Promise<this>;

  interface: MemoryAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorSnapshot: TypedContractMethod<
    [
      swarmId: string,
      rootHash: BytesLike,
      epochNumber: BigNumberish,
      label: string
    ],
    [void],
    "nonpayable"
  >;

  getLatestSnapshot: TypedContractMethod<
    [swarmId: string],
    [MemoryAnchor.MemorySnapshotStructOutput],
    "view"
  >;

  getSnapshotCount: TypedContractMethod<[swarmId: string], [bigint], "view">;

  getSnapshots: TypedContractMethod<
    [swarmId: string],
    [MemoryAnchor.MemorySnapshotStructOutput[]],
    "view"
  >;

  setSwarmGoal: TypedContractMethod<
    [swarmId: string, goal: string],
    [void],
    "nonpayable"
  >;

  snapshotCount: TypedContractMethod<[arg0: string], [bigint], "view">;

  snapshots: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, bigint, bigint, string, string] & {
        rootHash: string;
        epochNumber: bigint;
        timestamp: bigint;
        anchoredBy: string;
        label: string;
      }
    ],
    "view"
  >;

  swarmGoals: TypedContractMethod<[arg0: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorSnapshot"
  ): TypedContractMethod<
    [
      swarmId: string,
      rootHash: BytesLike,
      epochNumber: BigNumberish,
      label: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLatestSnapshot"
  ): TypedContractMethod<
    [swarmId: string],
    [MemoryAnchor.MemorySnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSnapshotCount"
  ): TypedContractMethod<[swarmId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSnapshots"
  ): TypedContractMethod<
    [swarmId: string],
    [MemoryAnchor.MemorySnapshotStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setSwarmGoal"
  ): TypedContractMethod<[swarmId: string, goal: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "snapshotCount"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "snapshots"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, bigint, bigint, string, string] & {
        rootHash: string;
        epochNumber: bigint;
        timestamp: bigint;
        anchoredBy: string;
        label: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "swarmGoals"
  ): TypedContractMethod<[arg0: string], [string], "view">;

  getEvent(
    key: "GoalSet"
  ): TypedContractEvent<
    GoalSetEvent.InputTuple,
    GoalSetEvent.OutputTuple,
    GoalSetEvent.OutputObject
  >;
  getEvent(
    key: "SnapshotAnchored"
  ): TypedContractEvent<
    SnapshotAnchoredEvent.InputTuple,
    SnapshotAnchoredEvent.OutputTuple,
    SnapshotAnchoredEvent.OutputObject
  >;

  filters: {
    "GoalSet(string,string,uint256)": TypedContractEvent<
      GoalSetEvent.InputTuple,
      GoalSetEvent.OutputTuple,
      GoalSetEvent.OutputObject
    >;
    GoalSet: TypedContractEvent<
      GoalSetEvent.InputTuple,
      GoalSetEvent.OutputTuple,
      GoalSetEvent.OutputObject
    >;

    "SnapshotAnchored(string,uint256,bytes32,uint256,address)": TypedContractEvent<
      SnapshotAnchoredEvent.InputTuple,
      SnapshotAnchoredEvent.OutputTuple,
      SnapshotAnchoredEvent.OutputObject
    >;
    SnapshotAnchored: TypedContractEvent<
      SnapshotAnchoredEvent.InputTuple,
      SnapshotAnchoredEvent.OutputTuple,
      SnapshotAnchoredEvent.OutputObject
    >;
  };
}
